services:
  postgres:
    image: postgres:17
    container_name: medalj-postgres
    environment:
      POSTGRES_DB: medalj
      POSTGRES_USER: medalj
      POSTGRES_PASSWORD: medalj
    ports:
      - "5432:5432"
    volumes:
      - medalj-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U medalj -d medalj" ]
      interval: 5s
      timeout: 5s
      retries: 10

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: >
      azurite
      --blobHost 0.0.0.0
      --queueHost 0.0.0.0
      --tableHost 0.0.0.0
      --location /data
      --skipApiVersionCheck
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite_data:/data


volumes:
  medalj-postgres-data:
  azurite_data:
