--liquibase formatted sql

--changeset anthon.haväng:002-seed-category-i-k runInTransaction:true

-- Browse groups
INSERT INTO browse_group (key, title_sv, title_en, display_order)
VALUES ('official_swedish', 'Officiella svenska utmärkelsetecken', 'Official Swedish decorations', 1),
       ('semi_official_swedish', 'Halvofficiella svenska utmärkelsetecken', 'Semi-official Swedish decorations', 2),
       ('swedish_without_state_emblem',
        'Svenska medaljer i medaljband som inte har H.M. Konungens bild och/eller statsemblem (krona)',
        'Swedish medal-ribbon decorations without H.M. the King''s portrait and/or state emblem (crown)', 3),
       ('foreign', 'Utländska utmärkelsetecken', 'Foreign decorations', 4),
       ('international', 'Internationella utmärkelsetecken', 'International decorations', 5);

-- Categories I and K
INSERT INTO category (browse_group_id, code, title_sv, title_en, display_order, is_expandable)
SELECT bg.id, 'I', 'Kategori I', 'Category I', 9, true
FROM browse_group bg
WHERE bg.key = 'official_swedish';

INSERT INTO category (browse_group_id, code, title_sv, title_en, display_order, is_expandable)
SELECT bg.id, 'K', 'Kategori K', 'Category K', 2, true
FROM browse_group bg
WHERE bg.key = 'semi_official_swedish';

-- Subcategories for I
WITH c AS (SELECT id FROM category WHERE code = 'I')
INSERT
INTO subcategory (category_id, key, title_sv, title_en, display_order)
SELECT c.id, s.key, s.title_sv, s.title_en, s.display_order
FROM c
         CROSS JOIN (VALUES ('i_grp_1',
                             'Övriga officiella medaljer som är instiftade eller godkända av Kungl. Maj:t, från 1975 av regeringen, och/eller delas ut av statliga myndigheter och akademier',
                             'Övriga officiella medaljer som är instiftade eller godkända av Kungl. Maj:t, från 1975 av regeringen, och/eller delas ut av statliga myndigheter och akademier',
                             1),
                            ('i_grp_2', 'Medaljer som är instiftade av Försvarsmakten: Grupp 1/Förtjänstmedaljer',
                             'Medaljer som är instiftade av Försvarsmakten: Grupp 1/Förtjänstmedaljer', 2),
                            ('i_grp_3', 'Medaljer som är instiftade av Försvarsmakten: Grupp 2/Tjänstgöringsmedaljer',
                             'Medaljer som är instiftade av Försvarsmakten: Grupp 2/Tjänstgöringsmedaljer', 3),
                            ('i_grp_4', 'Medaljer som är instiftade av andra svenska myndigheter',
                             'Medaljer som är instiftade av andra svenska myndigheter',
                             4)) AS s(key, title_sv, title_en, display_order);

-- Category I decorations (grouped)
WITH i_src(
           sub_key,
           item_order,
           name_sv, years,
           description_sv,
           abbr_pipe
    ) AS (VALUES ('i_grp_1', 1,
                  'Utmärkelsen för nit och redlighet i rikets tjänst',
                  '1803/1830/1857/1947/1973/1974/1979/1981',
                  NULL, 'NOR'),
                 ('i_grp_1', 2,
                  'Kungl. Krigsvetenskapsakademiens stora belöningsmedalj',
                  '1827/1995', NULL,
                  'KrVAGM|KrVASM'),
                 ('i_grp_1', 3,
                  'Kungl. Krigsvetenskapsakademiens belöningsmedalj',
                  '1829/1988/1995', NULL,
                  'KrVAgm|KrVAsm'),
                 ('i_grp_1', 4,
                  'Kungl. Ingenjörvetenskapsakademiens medalj',
                  '1921/1974/1987/1989/1996', NULL,
                  'IVAGM'),
                 ('i_grp_1', 5,
                  'Kungl. Universitetets i Uppsala medalj',
                  '1928', NULL, 'UUGM'),
                 ('i_grp_1', 6,
                  'Kungl. Musikaliska Akademiens förtjänstmedalj',
                  '1944', NULL, 'MusAGM'),
                 ('i_grp_1', 7,
                  'Kungl. Vitterhets-, Historie- och Antikvitetsakademiens Gustaf Adolfmedalj',
                  '1949/1985', NULL, 'HA:sGAM'),
                 ('i_grp_1', 8,
                  'Kungl. Vitterhets-, Historie- och Antikvitetsakademiens förtjänstmedalj',
                  '1967/1985', NULL,
                  'HA:sGM|HA:sSM'),
                 ('i_grp_1', 9,
                  'Utrikesdepartementets medalj för förtjänster inom utrikesförvaltningen',
                  '1976', NULL, 'GMutr'),
                 ('i_grp_1', 10,
                  'Kungl. Örlogsmannasällskapets belöningsmedalj',
                  NULL, NULL, 'KÖGM|KÖSM|KÖBM'),
                 ('i_grp_2', 1,
                  'Försvarsmaktens förtjänstmedalj (gult band)',
                  '1995', 'gult band',
                  'FMGMmsv|FMSMmsv|FMGM|FMSM'),
                 ('i_grp_2', 2,
                  'Försvarsmaktens belöningsmedalj med svärd för internationella insatser',
                  '1995', NULL,
                  'FMintbGMmsv|FMintbSMmsv'),
                 ('i_grp_2', 3,
                  'Försvarsmaktens förtjänstmedalj',
                  '2008', NULL, 'FMGM|FMSM'),
                 ('i_grp_3', 1,
                  'Försvarsmaktens grundutbildningsmedalj',
                  '2002/2010/2016',
                  'Tidigare FMvplM', 'FMGUSM'),
                 ('i_grp_3', 2,
                  'Försvarsmaktens reservofficersmedalj',
                  '2003/2008', NULL,
                  'FMresoffGM|FMresoffSM'),
                 ('i_grp_3', 3,
                  'Försvarsmaktens medalj för rikets försvar',
                  '2015', NULL,
                  'FMGSSGMm3kr|FMGSSGM|FMGSSSM|FMGSSBM'),
                 ('i_grp_3', 4,
                  'Försvarsmaktens medalj för internationella insatser',
                  '1991/1994/2012',
                  'med palm i guld för insats i Saudiarabien 1991; med korslagda spjut i brons för insats i Somalia 1992-93; med stjärna i guld för Swedish Release Hospital insats i Liberia 1992-1993; med lagerkrans i silver för insats i Forna Jugoslavien 1992; med lagerkrans i silver för insats i Georgien 1992; med dromedar i brons för insats i Afghanistan före 2003-08-11; okrans',
                  'FMintBM|FMintBMSaudi|FMintBMSom|FMintBMLib|FMintBMJug|FMintBMGeo|FMintBMAfg|FMintBMmbsp'),
                 ('i_grp_3', 5,
                  'Hemvärnets tjänstgöringsmedalj',
                  '2018',
                  'siffror beroende på antalet tjänstgöringsår',
                  'HvtjgSM|HvtjgGM|HvtjgGMemalj'),
                 ('i_grp_4', 1,
                  'Statens försvarshistoriska museers förtjänstmedalj',
                  '1995', NULL, 'SFHMGM|SFHMSM'),
                 ('i_grp_4', 2,
                  'Polisens guldmedalj i fredens tjänst',
                  '2000', NULL, 'SvPolisIntGM'),
                 ('i_grp_4', 3,
                  'Kriminalvårdens medalj för internationella insatser',
                  '2006', NULL, 'KVintSM'),
                 ('i_grp_4', 4,
                  'Försvarshögskolans förtjänstmedalj',
                  NULL, NULL, 'FHSGM|FHSSM|FHSBM'),
                 ('i_grp_4', 5,
                  'Försvarets radioanstalts förtjänstmedalj för internationella insatser',
                  '2010', NULL, 'FRAintSM'),
                 ('i_grp_4', 6,
                  'Försvarets radioanstalts förtjänstmedalj',
                  '2010', NULL, 'FRAGM|FRASM'),
                 ('i_grp_4', 7,
                  'Försvarets materielverks förtjänstmedalj',
                  '2010', NULL,
                  'FMVGM|FMVSM|FMVBM'),
                 ('i_grp_4', 8,
                  'Polismyndighetens medalj för förtjänstfulla insatser',
                  '2017', NULL,
                  'PolismGM|PolismSM'),
                 ('i_grp_4', 9,
                  'Polismyndighetens medalj för rådigt ingripande',
                  '2017', NULL,
                  'PolismMedborgGM|PolismMedborgGM'),
                 ('i_grp_4', 10,
                  'Tullverkets förtjänstmedalj',
                  '2018', NULL, 'TullvGM')),
     c AS (SELECT id FROM category WHERE code = 'I'),
     s AS (SELECT s.id, s.key
           FROM subcategory s
                    JOIN c ON c.id = s.category_id)
INSERT
INTO decoration (category_id, subcategory_id, name_sv, name_en, initial_number,
                 year_display, year_sort, description_sv, description_en, display_order)
SELECT NULL,
       s.id,
       i.name_sv,
       i.name_sv,
       NULL,
       i.years,
       NULL,
       i.description_sv,
       i.description_sv,
       i.item_order
FROM i_src i
         JOIN s ON s.key = i.sub_key;

-- I short_codes
WITH i_src(
           sub_key,
           item_order,
           abbr_pipe
    ) AS (VALUES ('i_grp_1', 1, 'NOR'),
                 ('i_grp_1', 2, 'KrVAGM|KrVASM'),
                 ('i_grp_1', 3, 'KrVAgm|KrVAsm'),
                 ('i_grp_1', 4, 'IVAGM'),
                 ('i_grp_1', 5, 'UUGM'),
                 ('i_grp_1', 6, 'MusAGM'),
                 ('i_grp_1', 7, 'HA:sGAM'),
                 ('i_grp_1', 8, 'HA:sGM|HA:sSM'),
                 ('i_grp_1', 9, 'GMutr'),
                 ('i_grp_1', 10, 'KÖGM|KÖSM|KÖBM'),
                 ('i_grp_2', 1, 'FMGMmsv|FMSMmsv|FMGM|FMSM'),
                 ('i_grp_2', 2, 'FMintbGMmsv|FMintbSMmsv'),
                 ('i_grp_2', 3, 'FMGM|FMSM'),
                 ('i_grp_3', 1, 'FMGUSM'),
                 ('i_grp_3', 2, 'FMresoffGM|FMresoffSM'),
                 ('i_grp_3', 3, 'FMGSSGMm3kr|FMGSSGM|FMGSSSM|FMGSSBM'),
                 ('i_grp_3', 4,
                  'FMintBM|FMintBMSaudi|FMintBMSom|FMintBMLib|FMintBMJug|FMintBMGeo|FMintBMAfg|FMintBMmbsp'),
                 ('i_grp_3', 5, 'HvtjgSM|HvtjgGM|HvtjgGMemalj'),
                 ('i_grp_4', 1, 'SFHMGM|SFHMSM'),
                 ('i_grp_4', 2, 'SvPolisIntGM'),
                 ('i_grp_4', 3, 'KVintSM'),
                 ('i_grp_4', 4, 'FHSGM|FHSSM|FHSBM'),
                 ('i_grp_4', 5, 'FRAintSM'),
                 ('i_grp_4', 6, 'FRAGM|FRASM'),
                 ('i_grp_4', 7, 'FMVGM|FMVSM|FMVBM'),
                 ('i_grp_4', 8, 'PolismGM|PolismSM'),
                 ('i_grp_4', 9, 'PolismMedborgGM|PolismMedborgGM'),
                 ('i_grp_4', 10, 'TullvGM'))
INSERT
INTO decoration_short_code (decoration_id, short_code, display_order, description_sv, description_en)
SELECT d.id,
       trim(a.abbr),
       a.ord::int,
       NULL,
       NULL
FROM i_src i
         JOIN category c ON c.code = 'I'
         JOIN subcategory s ON s.category_id = c.id AND s.key = i.sub_key
         JOIN decoration d ON d.subcategory_id = s.id AND d.display_order = i.item_order
         CROSS JOIN LATERAL unnest(string_to_array(i.abbr_pipe, '|')) WITH ORDINALITY AS a(abbr, ord);

-- Category K (numbered, no year)
WITH k_src(
           initial_number,
           display_order,
           name_sv,
           description_sv,
           abbr_pipe
    ) AS (VALUES (1, 1,
                  'Kungl. Patriotiska Sällskapets belöningsmedalj',
                  NULL,
                  'PatrSstGM|PatrSstSM2|PatrSstSM3'),
                 (2, 2,
                  'Kungl. Sällskapet Pro Patrias belöningsmedalj',
                  NULL, 'ProPstGM|ProPstSM'),
                 (3, 3,
                  'Svenska Jägareförbundets belöningsmedalj',
                  NULL, 'SvJägfbGM|SvJägfbSM'),
                 (4, 4,
                  'Kungl. Svenska Segelsällskapets medalj',
                  NULL, 'KSSSGM|KSSSSM'),
                 (5, 5,
                  'Svenska Röda Korsets förtjänstmedalj',
                  NULL, 'SRKGM8|SRKSM'),
                 (6, 6,
                  'Centralförbundet för befälsutbildning förtjänstmedalj',
                  NULL, 'CFBGM|CFBSM'),
                 (7, 7,
                  'Kungl. Motorbåtsklubbens förtjänstmedalj',
                  NULL, 'KMKGM'),
                 (8, 8,
                  'Svenska sportskytteförbundets förtjänstmedalj',
                  NULL,
                  'SvSpsfbJrM|SvSpsfbGM|SvSpsfbSM'),
                 (9, 9,
                  'Sjövärnskårernas Riksförbunds förtjänstmedalj',
                  NULL, 'SVKGM|SVKSM'),
                 (10, 10,
                  'Skytteförbundens överstyrelses förtjänstmedalj',
                  NULL, 'SfbÖSGM|SfbÖSSM'),
                 (11, 11,
                  'Svenska Blå Stjärnans förtjänstmedalj',
                  NULL, 'SBSGM|SBSSM'),
                 (12, 12,
                  'Frivilliga Automobilkårernas Riksförbunds förtjänstmedalj',
                  NULL, 'FAKGM|FAKSM'),
                 (13, 13,
                  'Sveriges Orkesterföreningars riksförbunds förtjänstmedalj',
                  'före 1976 förtjänsttecken',
                  'SORfbGM|SORfbSM'),
                 (14, 14,
                  'Kungl. Svenska Segelsällskapets rorsmedalj',
                  NULL, 'KSSSrGM|KSSSrSM'),
                 (15, 15,
                  'Svenska Kennelklubbens förtjänstmedalj',
                  NULL, 'SvKKGM|SvKKSM'),
                 (16, 16,
                  'Kungl. Svenska Aeroklubbens förtjänstmedalj',
                  NULL,
                  'KSAKGMmv|KSAKSMmv|KSAKGM|KSAKSM|KSAKGM5mv|KSAKSM5mv|KSAKGM5|KSAKSM5'),
                 (17, 17,
                  'Frivilliga Motorcykelkårernas Riksförbunds förtjänstmedalj',
                  'före 1972 Frivilliga Motorcykelkårens förtjänstmedalj',
                  'FMCKGM|FMCKSM'),
                 (18, 18,
                  'Sveriges Civilförsvarsförbunds förtjänstmedalj',
                  'före 1951 Sveriges Riksförbund för civilt luftskydd/Riksluftskyddsförbundets förtjänstmedalj',
                  'SCFGM|SCFSM'),
                 (19, 19,
                  'Kungl. Automobil Klubbens förtjänstmedalj',
                  NULL, 'KAKGM'),
                 (20, 20,
                  'Sveriges Militäridrotts- och Mångkampsförbunds förtjänstmedalj',
                  'före 1987 Sveriges Militära Idrottsförbunds förtjänstmedalj',
                  'SMIGM|SMISM'),
                 (21, 21,
                  'Riksförbundet Sveriges Lottakårers kungliga förtjänstmedalj',
                  NULL, 'SLKGM|SLKSM'),
                 (22, 22,
                  'Föreningen Sveriges Flottas förtjänstmedalj',
                  NULL, 'FSvFIGM|FSvFISM'),
                 (23, 23,
                  'Riksföreningens för Simningens främjande/Simfrämjandets förtjänstmedalj',
                  NULL, 'RfSimGM|RfSimSM'),
                 (24, 24,
                  'Hemvärnets förtjänstmedalj',
                  NULL, 'HVGM|HVSM'),
                 (25, 25,
                  'Riksförbundet Sveriges Amatörorkestrars förtjänstmedalj',
                  'före 1958 riksförbundet Sveriges Amatörmusikkårers förtjänstmedalj',
                  'RSAOG'),
                 (26, 26,
                  'Andra Lingiadens minnesmedalj',
                  NULL, 'LingGM'),
                 (27, 27,
                  'Sveriges Ungdomsberedskaps förtjänstmedalj',
                  NULL, 'SvUbGM'),
                 (28, 28,
                  'Svenska Brandförsvarsföreningens förtjänstmedalj',
                  'före 1964 Svenska brandkårernas riksförbunds förtjänstmedalj',
                  'SvBrffGM8msp|SvBrffGM8|SvBrffGM5msp|SvBrffGM5'),
                 (29, 29,
                  'Sveriges Motorfederations kungliga medalj',
                  NULL, 'MotorfedGM'),
                 (30, 30,
                  'Sveriges Riksidrottsförbunds jubileumsmedalj',
                  NULL, 'SvrifbJGM'),
                 (31, 31,
                  'Svenska Fotbollsförbundets förtjänstmedalj med anledning av världsmästerskapstävlingarna i fotboll 1958',
                  NULL, 'VMFGM'),
                 (32, 32,
                  'Svenska ridsportförbundets förtjänstmedalj',
                  'före 1994 Riksföreningens för ridningens främjande/Ridfrämjandets förtjänstmedalj',
                  'SvRsfGM|SvRsfSM'),
                 (33, 33,
                  'Svenska Polisens idrotts- och Skytteförbunds förtjänstmedalj',
                  NULL, 'SvPISGM|SvPISSM'),
                 (34, 34,
                  'Sveriges Bilkårers kungliga medalj',
                  'f.d. Sveriges Kvinnliga Bilkårers kungliga medalj',
                  'SKBRGM|SKBRSM'),
                 (35, 35,
                  'Nationalföreningen för trafiksäkerhetens främjande förtjänstmedalj',
                  NULL, 'NTFGM'),
                 (36, 36,
                  'Officerarnas Målskjutningsförbund i Stockholm förtjänstmedalj',
                  NULL,
                  'OffmfbSthGM|OffmfbSthSM'),
                 (37, 37,
                  'Svenska Pistolskytteförbundets förtjänstmedalj',
                  NULL,
                  'SvPistsfbGM|SvPistsfbSM'),
                 (38, 38,
                  'Simfrämjandets förtjänstmedalj',
                  'före 1973 Svenska Livräddningssällskapets förtjänstmedalj',
                  'Svls-SimGM|Svls-SimSM'),
                 (39, 39,
                  'Frivilliga Radioorganisationens särskilda förtjänstmedalj',
                  NULL, 'FROGM|FROSM'),
                 (40, 40,
                  'Svenska Fäktförbundets Kungliga förtjänstmedalj',
                  NULL, 'SvFfbGM|SvFfbSM'),
                 (41, 41,
                  'Föreningen Sveriges Sjöfart och Sjöförsvars förtjänsttecken',
                  NULL, 'FSSSGft|FSSSGft'),
                 (42, 42,
                  'Flygvapenföreningarnas Riksförbunds förtjänstmedalj',
                  NULL, 'FVRFGM|FVRFGM'),
                 (43, 43,
                  'Svenska Värnpliktofficersförbundets kungliga förtjänstmedalj',
                  NULL, 'SVOFGFM'),
                 (44, 44,
                  'Stiftelsen Sveriges Nationaldag och Svenska flaggans dag Kungliga förtjänstmedalj',
                  NULL, 'SSNDGM'),
                 (45, 45,
                  'Hemvärnsbefälets Riksförbunds kungliga medalj',
                  NULL, 'HBRGM')),
     kcat AS (SELECT id FROM category WHERE code = 'K')
INSERT
INTO decoration (category_id, subcategory_id, name_sv, name_en, initial_number,
                 year_display, year_sort, description_sv, description_en, display_order)
SELECT kcat.id,
       NULL,
       k.name_sv,
       k.name_sv,
       k.initial_number,
       NULL,
       NULL,
       k.description_sv,
       k.description_sv,
       k.display_order
FROM k_src k
         CROSS JOIN kcat;

-- K short_codes
WITH k_src(
           initial_number,
           abbr_pipe
    ) AS (VALUES (1, 'PatrSstGM|PatrSstSM2|PatrSstSM3'),
                 (2, 'ProPstGM|ProPstSM'),
                 (3, 'SvJägfbGM|SvJägfbSM'),
                 (4, 'KSSSGM|KSSSSM'),
                 (5, 'SRKGM8|SRKSM'),
                 (6, 'CFBGM|CFBSM'),
                 (7, 'KMKGM'),
                 (8, 'SvSpsfbJrM|SvSpsfbGM|SvSpsfbSM'),
                 (9, 'SVKGM|SVKSM'),
                 (10, 'SfbÖSGM|SfbÖSSM'),
                 (11, 'SBSGM|SBSSM'),
                 (12, 'FAKGM|FAKSM'),
                 (13, 'SORfbGM|SORfbSM'),
                 (14, 'KSSSrGM|KSSSrSM'),
                 (15, 'SvKKGM|SvKKSM'),
                 (16,
                  'KSAKGMmv|KSAKSMmv|KSAKGM|KSAKSM|KSAKGM5mv|KSAKSM5mv|KSAKGM5|KSAKSM5'),
                 (17, 'FMCKGM|FMCKSM'),
                 (18, 'SCFGM|SCFSM'),
                 (19, 'KAKGM'),
                 (20, 'SMIGM|SMISM'),
                 (21, 'SLKGM|SLKSM'),
                 (22, 'FSvFIGM|FSvFISM'),
                 (23, 'RfSimGM|RfSimSM'),
                 (24, 'HVGM|HVSM'),
                 (25, 'RSAOG'),
                 (26, 'LingGM'),
                 (27, 'SvUbGM'),
                 (28, 'SvBrffGM8msp|SvBrffGM8|SvBrffGM5msp|SvBrffGM5'),
                 (29, 'MotorfedGM'),
                 (30, 'SvrifbJGM'),
                 (31, 'VMFGM'),
                 (32, 'SvRsfGM|SvRsfSM'),
                 (33, 'SvPISGM|SvPISSM'),
                 (34, 'SKBRGM|SKBRSM'),
                 (35, 'NTFGM'),
                 (36, 'OffmfbSthGM|OffmfbSthSM'),
                 (37, 'SvPistsfbGM|SvPistsfbSM'),
                 (38, 'Svls-SimGM|Svls-SimSM'),
                 (39, 'FROGM|FROSM'),
                 (40, 'SvFfbGM|SvFfbSM'),
                 (41, 'FSSSGft|FSSSGft'),
                 (42, 'FVRFGM|FVRFGM'),
                 (43, 'SVOFGFM'),
                 (44, 'SSNDGM'),
                 (45, 'HBRGM'))
INSERT
INTO decoration_short_code (decoration_id, short_code, display_order, description_sv, description_en)
SELECT d.id,
       trim(a.abbr),
       a.ord::int,
       NULL,
       NULL
FROM k_src k
         JOIN category c ON c.code = 'K'
         JOIN decoration d ON d.category_id = c.id AND d.initial_number = k.initial_number
         CROSS JOIN LATERAL unnest(string_to_array(k.abbr_pipe, '|')) WITH ORDINALITY AS a(abbr, ord);
