--liquibase formatted sql

--changeset anthon.havang:003-convert-serial-to-identity runInTransaction:true splitStatements:false

-- browse_group
ALTER TABLE browse_group
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

DO
$$
    DECLARE
        v_next bigint;
    BEGIN
        SELECT COALESCE(MAX(id), 0) + 1 INTO v_next FROM browse_group;
        EXECUTE format('ALTER TABLE browse_group ALTER COLUMN id RESTART WITH %s', v_next);
    END
$$;

-- category
ALTER TABLE category
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

DO
$$
    DECLARE
        v_next bigint;
    BEGIN
        SELECT COALESCE(MAX(id), 0) + 1 INTO v_next FROM category;
        EXECUTE format('ALTER TABLE category ALTER COLUMN id RESTART WITH %s', v_next);
    END
$$;

-- subcategory
ALTER TABLE subcategory
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

DO
$$
    DECLARE
        v_next bigint;
    BEGIN
        SELECT COALESCE(MAX(id), 0) + 1 INTO v_next FROM subcategory;
        EXECUTE format('ALTER TABLE subcategory ALTER COLUMN id RESTART WITH %s', v_next);
    END
$$;

-- decoration
ALTER TABLE decoration
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

DO
$$
    DECLARE
        v_next bigint;
    BEGIN
        SELECT COALESCE(MAX(id), 0) + 1 INTO v_next FROM decoration;
        EXECUTE format('ALTER TABLE decoration ALTER COLUMN id RESTART WITH %s', v_next);
    END
$$;

-- decoration_short_code
ALTER TABLE decoration_short_code
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

DO
$$
    DECLARE
        v_next bigint;
    BEGIN
        SELECT COALESCE(MAX(id), 0) + 1 INTO v_next FROM decoration_short_code;
        EXECUTE format('ALTER TABLE decoration_short_code ALTER COLUMN id RESTART WITH %s', v_next);
    END
$$;

-- decoration_ribbon_image
ALTER TABLE decoration_ribbon_image
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

DO
$$
    DECLARE
        v_next bigint;
    BEGIN
        SELECT COALESCE(MAX(id), 0) + 1 INTO v_next FROM decoration_ribbon_image;
        EXECUTE format('ALTER TABLE decoration_ribbon_image ALTER COLUMN id RESTART WITH %s', v_next);
    END
$$;

-- decoration_medal_image
ALTER TABLE decoration_medal_image
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

DO
$$
    DECLARE
        v_next bigint;
    BEGIN
        SELECT COALESCE(MAX(id), 0) + 1 INTO v_next FROM decoration_medal_image;
        EXECUTE format('ALTER TABLE decoration_medal_image ALTER COLUMN id RESTART WITH %s', v_next);
    END
$$;
