--liquibase formatted sql

--changeset anthon.havang:006-seed-category-l runInTransaction:true splitStatements:false
--preconditions onFail:HALT
--precondition-sql-check expectedResult:1 SELECT COUNT(*) FROM browse_group WHERE key = 'swedish_without_state_emblem';

CREATE TABLE IF NOT EXISTS decoration_category_l_detail
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decoration_id       BIGINT      NOT NULL UNIQUE REFERENCES decoration (id) ON DELETE CASCADE,
    source_model        TEXT        NOT NULL CHECK (source_model IN ('legacy', 'primary', 'initial-number')),
    award_levels        TEXT,
    medal_size          TEXT,
    raw_short_code_text TEXT,
    source_line_no      INTEGER     NOT NULL CHECK (source_line_no > 0),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO category (browse_group_id, code, title_sv, title_en, display_order, is_expandable)
SELECT bg.id, 'L', 'Kategori L', 'Category L', 1, true
FROM browse_group bg
WHERE bg.key = 'swedish_without_state_emblem'
  AND NOT EXISTS (SELECT 1 FROM category WHERE code = 'L');

WITH c AS (SELECT id FROM category WHERE code = 'L')
INSERT
INTO subcategory (category_id, key, title_sv, title_en, display_order)
SELECT c.id, s.key, s.title_sv, s.title_en, s.display_order
FROM c
         CROSS JOIN (VALUES ('l_grp_1', 'Övriga icke officiella förtjänstmedaljer i kategori L',
                             'Övriga icke officiella förtjänstmedaljer i kategori L', 1),
                            ('l_grp_2', 'Minnesmedaljer i kategori L', 'Minnesmedaljer i kategori L', 2),
                            ('l_grp_3', 'Särskilda svenska utmärkelsetecken utan band',
                             'Särskilda svenska utmärkelsetecken utan band',
                             3)) AS s(key, title_sv, title_en, display_order)
WHERE NOT EXISTS (SELECT 1
                  FROM subcategory existing
                  WHERE existing.category_id = c.id
                    AND existing.key = s.key);

DO
$plpgsql$
    DECLARE
        src_line_no            integer;
        raw_line               text;
        section                text    := 'l_grp_1';
        parts                  text[];
        category_l_id          bigint;
        subcategory_group_1_id bigint;
        subcategory_group_2_id bigint;
        subcategory_group_3_id bigint;
        inserted_decoration_id bigint;
        primary_display_order  integer := 0;
        group_1_display_order  integer := 0;
        group_2_display_order  integer := 0;
        group_3_display_order  integer := 0;
    BEGIN
        SELECT id
        INTO category_l_id
        FROM category
        WHERE code = 'L';

        SELECT s.id
        INTO subcategory_group_1_id
        FROM subcategory s
                 JOIN category c ON c.id = s.category_id
        WHERE c.code = 'L'
          AND s.key = 'l_grp_1';

        SELECT s.id
        INTO subcategory_group_2_id
        FROM subcategory s
                 JOIN category c ON c.id = s.category_id
        WHERE c.code = 'L'
          AND s.key = 'l_grp_2';

        SELECT s.id
        INTO subcategory_group_3_id
        FROM subcategory s
                 JOIN category c ON c.id = s.category_id
        WHERE c.code = 'L'
          AND s.key = 'l_grp_3';

        FOR src_line_no, raw_line IN
            SELECT ordinality::int,
                   trim(both E'\r' FROM line)
            FROM regexp_split_to_table($category_l$
Kungl. Patriotiska Sällskapets Emmerymedalj	G/S	11	PatrSEGM/SM	1786
Friluftsfrämjandets förtjänstmedalj	J/G/S	11	FrilJrM/GM/SM	1899
Sveriges Centralförenings för idrottens främjande förtjänstmedalj	G/S	9	SvcfiGM/SM	1907
Svenska Gymnastikförbundets förtjänstmedalj	G/S	8	SvGymnfbLingGM/SM	1907
Sveriges Riksidrottsförbunds förtjänstmedalj	G/S	8	SvrifbGM/SM	1910
Södra Skånska regementets och Malmö försvarsområdes förtjänstmedalj	G/S	12	SSkånregGM/SM	1913
Svenska Skidförbundets förtjänstmedalj	G/S	8	SvSkidfbGM/SM	1914
Föreningen för befrämjande av skolungdomens vapenövningar/Skol-Skyttefrämjandets förtjänstmedalj	G/S/B	8	SkolVGM/SM/BM	1918
Centralförbundet för befälsutbildning förtjänsttecken	G/S	8	CFBGM/SM	1922
Upplands Befälsutbildningsförbunds förtjänstmedalj	G/S	8	UpplbfbGM/SM	1924
Förbundet Kustjägarna förtjänstmedalj	G/S	8	KjbfbGM/SM	1924
Blekinge Befälsutbildningsförbunds förtjänstmedalj	G/S	8	BlebfbGM/SM	1924
Bohuslän-Dal Befälsutbildningsförbunds förtjänstmedalj	G/S	8	BohusDalbfbGM/SM	1924
Göteborg och Bohuslän Befälsutbildningsförbunds förtjänstmedalj	G/S	8	GbgBohusbfbGM/SM	1924
Malmöhus läns Befälsutbildningsförbunds förtjänstmedalj	G/S	8	MalmöhusbfbGM/SM	1924
Dalarna Befälsutbildningsförbunds förtjänstmedalj	G/S	8	DalabfbGM/SM	1924
Västernorrland Befälsutbildningsförbunds förtjänstmedalj	G/S	8	VNNbfbGM/SM	1924
Norrköpings försvarsområdes Befälsutbildningsförbunds	G/S	8	NorrkfobfbGM/SM	1924
Gotlands Befälsutbildningsförbunds förtjänstmedalj	G/S	8	GotbfbGM/SM	1924
Norrbotten Östra Befälsutbildningsförbunds förtjänstmedalj	G/S	8	NorrbÖbfbGM/SM	1924
Försvarsutbildarna Norrbotten Norra förtjänstmedalj	G/S	8	NorrbNbfbGM/SM	1924
Försvarsutbildarna Norra Småland förtjänstmedalj	G/S	8	NorraSmåbfbGM/S	1924
Försvarsutbildarna Norrbotten Södra förtjänstmedalj	G/S	8	NorrbSbfbGM/SM	1924
Försvarsutbildarna Värmland förtjänstmedalj	G/S	8	VärmlfuGM/SM	1924
Försvarsutbildarna Östergötland förtjänstmedalj	G/S	8	ÖstergötfuGM/SM	1924
Försvarsutbildarna Kronoberg förtjänstmedalj	G/S	8	KronobtfuGM/SM	1924
Försvarsutbildarna Jämtland förtjänstmedalj	G/S	8	JämtlfuGM/SM	1924
Försvarsutbildarna Västerbotten förtjänstmedalj	G/S	8	VästerbfuGM/SM	1924
Värnpliktiga Officerares Riksförbunds hederstecken	G/S	8	VoffRfbGHt/SHt	1926
Sportskytteförbunds (distriktsorganisation) förtjänstmedalj	G/S	8	…spsfbGM/SM	1927
Sjövärnsflottiljs förtjänstmedalj	G/S	8	SVKGM/SM	1929
Svenska Fäktförbundets förtjänstmedalj	G/S/B	8	SvFfbGM/SM/BM	1931
Svenska Reservunderofficersförbundets förtjänsttecken	G/S	8	SvRuoffGft/Sft	1932
Frivilliga Automobilkårernas Riksförbunds hederstecken G/S		8	FAKGft/Sft	1934
Förbundet Sveriges Reservofficerares hederstecken (f.d. Svenska Arméns och flygvapnets reservofficersförbunds hederstecken)	G/S	8	SVEROFGHt/Sht	1934
Livregementets Grenadjärers förtjänsttecken	G/S/B	8	LivreggrenGM/SM/BM	1937
Svenska Brukshundsklubbens medalj för gagnerik kynologisk verksamhet	G	8	SBKkynGM	1940
Svenska Brukshundklubbens förtjänstmedalj	G/S	8	SBKgm/sm	1940
Kustartilleriets reservofficersförbunds hederstecken	G/S/B	8	KAROFFGHt/SHt/BHt	1941/1999
Sveriges Civilförsvarsförbunds förtjänsttecken	G/S/B	8	SCFGFt/SFt/BFt	1941
Svea Artilleriregementes förtjänstmedalj	G/S	8	SveaartregGM/SM	1943
Stockholms Läns Försvarskommittés förtjänstmedalj	G/S/B	8	SthFKGM/SM/BM	1943
Sveriges Militäridrotts- och Mångkampsförbunds förtjänstmedalj med krans	G/S	8	SMIGM/SM	1943
Riksförbundet Sveriges lottakårers förtjänstmedalj	S	8	SLKsm	1944
Svenska Röda Korsets förtjänsttecken	S	8	SRKSFt	1944
Stockholms Luftvärnsförenings förtjänstmedalj	G/S	8	SthlvGM/SM	1944
Pistolskyttekrets förtjänstmedalj	G/S	8	…pistskGM/SM	1944
Hemvärnets Petrimedalj	S/B	8	HvPetriSM/BM	1945
Svenska Korporationsidrottsförbundets förtjänstmedalj	G/S/B	8	SvKifbGM/SM/BM	1946
Gotlands artilleriregementes förtjänstmedalj	G/S	8	GotartregGM/SM	1947
Svenska blå Stjärnans förtjänsttecken med stjärna	S	8	SBSSFtmstj	1947
Svenska blå Stjärnans förtjänsttecken	S	8	SBSSFt	1947
Föreningens för arbetarskydd förtjänsttecken	G	8	FArbskGFt	1949
Kamratföreningen bergslagsartilleristers förtjänstmedalj	S	8	KBergartSM	1950
Svenska Brandförsvarsföreningens förtjänsttecken	G	8	SvBrffGFt	1950
Svenska Flottans Reservofficersförbunds hederstecken	G	8	SvFLRoffHt	1951
Svenska Värnpliktsofficersförbundets förtjänstmedalj	G/S/B	8	SVOFGM/SM/BM	1954
Kamratförbundets för Svenska Koreaambulansen minnes- och förtjänstkors	S	Kors	KSKASK	1954
Förbundet Svenska Finlandsfrivilligas frivilligkors	G/S	Kors	SvFinlfrivGk/Sk	1955
Skytteförbundens överstyrelses Bernadottemedalj	G	8	SfbÖSBernGM	1955
Ryttarolympiadens 1956 förtjänsttecken	G	13	RyttarOlympFt	1956
Svenska Ridsportens Centralförbunds förtjänstmedalj	G/S	8	SRCfbGM/SM	1957
Flygvapenföreningarnas Riksförbunds förtjänstmedalj	G/S	8	FVRFgm/sm	1957/1964
Hälsinge regementes förtjänstmedalj	G/S	8	HälsregGM/SM	1959
Nationalföreningens för trafiksäkerhetens främjande förtjänsttecken	G/S	8	NTFGFt/SFt	1959
Försvarets Civila Idrottsförbunds förtjänstmedalj	G/S	8	FCIGM/SM	1960
Tullens Militära Befälsförenings förtjänstmedalj	G/S	8	TMBFGM/SM	1960
Frivilliga Radioorganisationens förtjänstmedalj	G/S/B	8	FROgm/sm/bm	1961
Sjövärnskårernas förtjänsttecken	S	8	SVKSFt	1961
Sveriges Militära kamratföreningars riksförbunds förtjänsttecken	G/S	8	SvMilkfGft/Sft	1961
Sveriges Kvinnliga Bilkårers riksförbunds förtjänstmedalj	G	8	SKBRGM	1963
Försvarets Motorklubbs förtjänstmedalj	G/S	8	FMKGM/SM	1963
Norrbottens regementes förtjänstmedalj	G/S/B	8	NorrbregGM/SM/BM	1967
Förbundet Sveriges Reservofficerares förtjänsttecken	G/S	8	SVEROFGFt/SFt	1969/2001
Kronobergs regementes hedersmedalj	G/S/B	8	KronobregGM/SM/BM	1971
Borås Hemvärnsområdes förtjänstmedalj	S	8	BoråshvoSM	1971
Militärmusiksamfundets förtjänstmedalj	G/S	8	MMSGM/SM	1971
Militärmusiksamfundets minnesmedalj	G	8	MMSMGM	1971
Helsingborgs Försvarskommittés förtjänstmedalj	G/S/B	8	HFKGM/SM/BM	1971
Västernorrlands regementes och Ångermanlandsbrigadens förtjänstmedalj	G/S	8	VnorrregÅngbrigGM/SM	1974
Föreningen Flottans Mäns hedersankare	G	8	FFlMGHa	1975
Norrbottens arméflygbataljons förtjänsttecken	G/S	8	NorrbafbatGM/SM	1980
Svenska Officersförbundets förtjänstmedalj	S	8	SvOffSM	1980
Frivilliga Motorcykelkårernas Riksförbunds förtjänsttecken	G/S	8	FMCKGFt/SFt	1986
Svenska Värnpliktsofficersförbundets förtjänsttecken	S	8	SVOFSFt	1987
Svenska Brukshundklubbens förtjänsttecken	G	8	SBKGFt	1988
Bodens artilleriregementes hedersmedalj	G	8	BodensartregGM	1989
Kalix försvarsområdes förtjänstmedalj	G/S	8	Fo67GM/SM	1989
Gotlands luftvärnsbataljons hedersmedalj	G	8	GotlvbatGM	1990
Södermanlands försvarsområdes förtjänstmedalj	G/S	8	SödFoGM/SM	1990
Ryttar VM 1990 förtjänstmedalj	G	13	RyttarVMGM	1990
Ryttar VM 1990 förtjänstmedalj	S	8	RyttarVMSM	1990
Gotlands regementes hedersmedalj	G/S	8	GotregGM/SM	1991/2018
Bergslagens artilleriregementes förtjänstmedalj	S	8	BergslartregSM	1991
Hemvärnsbefälets riksförbunds förtjänsttecken	G	8	HBRGFt	1991
Frivilliga flygkårens förtjänstmedalj	G/S	8	FFKGM/SM	1991
Hälsinge regementes förtjänstmedalj	G/S	8	HälsingeregGM/SM	1993
Livgardets Dragoners förtjänstmedalj	G/S	8	LGDGM/SM	1993
Väg- och vattenbyggnadskåren förtjänstmedalj	G/S	8	VVKGM/SM	1993
Föreningen Flottans Mäns ankarmedalj	G/S	8	FFlMGAm/SAm	1993
Norrbottens gränsjägares förtjänstmedalj	G/S	8	NorrbgrjGM/SM	1994
Värmlandsbrigadens förtjänsttecken	G	8	VärmlbrigGft	1994
Värmlands regementes förtjänsttecken	G	8	VärmlregGft	1994
Älvsborgsbrigadens förtjänstmedalj	G	8	ÄlvsbbrigGM	1994
Skånska dragonregementets förtjänstmedalj	G/S	8	SkåndragregGM/SM	1994
Skånska dragonregementets förtjänstmedalj	B	8	SkåndragregBM	1994
Norrlands trängkårs hedersmedalj	S/B	8	NorrltrkårSM/BM	1994
Bodens försvarsområdes hedersmedalj	S	8	Fo63hM	1994
Bodens artilleriregementes hedersmedalj	S	8	BartreghM	1994
Bodens försvarsområdes hedersmedalj	S	8	BodensfoSM	1994
Byggnads- och reparationsberedskapens förtjänstmedalj	G/S	8	BRBGM/SM	1994
Kraftvärnets förtjänstmedalj	G	8	KraftvGM	1994
Blå barettförtjänstmedaljen	B	6	BbarettBM	1995
Dalabrigadens förtjänstmedalj	G/S/B	8	DalbrigGM/SM/BM	1995
Hallandsbrigadens förtjänstmedalj	G/S	8	HallbrigGM/SM	1995
Arméns luftvärnscentrums hedersmedalj	S	8	LvcSM	1995
Mellersta arméfördelningens förtjänstmedalj	S	8	MellfördSM	1995
Järnvägarnas driftvärns förtjänstmedalj	G/S	8	JvgDvGM/SM	1995
Handelskammarens för Örebro och Västmanlands län förtjänstmedalj	G/S	8	HkÖV:slänGftjM/SftjM	1995
Dalregementets förtjänstmedalj	G/S/B	8	DalregGM/SM/BM	1996
Norrbottens flygflottiljs förtjänstmedalj	G	8	NorrbffljGM	1996
Fredsbaskrarna Sverige/Kamratföreningen bataljonens förtjänstmedalj	G/S	8	KamratfbatGM/SM	1996
Officersförbundets förtjänstmedalj	S	8	OffSM	1996
Flygfältsingenjörernas förtjänstmedalj	G/S	8	FFIGM/SM	1998
Norrlands Signalkårs förtjänstmedalj	S	8	NorrsignSM	1998
Svea livgardes förtjänstmedalj	G/S	8	SLGGM/SM	1999
Skaraborgs regementes och Skaraborgsbrigadens förtjänstmedalj	G/S	8	SkarabregbrigGM/SM	1999
Jämtlands flygflottiljs förtjänstmedalj	G/S	8	JämtffljGM/SM	1999
Livregementets Husarers förtjänstmedalj	G/S	8	LivreghusGM/SM	2000
Upplands regementes förtjänstmedalj	G/S	8	UpplregGM/SM	2000
Marinbasens förtjänstmedalj	G/S	8	MarinBGM/SM	2000
Amfibieregementets förtjänstmedalj	G/S	8	AmfregGM/SM	2000
Älvsborgs amfibieregementes förtjänstmedalj	G/S	8	ÄlvsbamfregGM/SM	2000
Försvarsmaktens logistik förtjänstmedalj	S	8	FMLOGSM	2000
Topografiska föreningens förtjänstmedalj	G/S	8	ToPFGM/SM	2000
Artilleriregementets förtjänstmedalj	G/S	8	ArtregGM/SM	2001
Luftvärnsregementets förtjänstmedalj	G/S	8	LvregGM/SM	2001
Totalförsvarets psykförsvarsförbunds förtjänstmedalj	G/S	8	ToPFGM/SM	2001
Södra militärdistriktets förtjänstmedalj	G/S	8	MSDGM/SM	2001
Riddarhusets medalj	G	12	RhGGM12	2002/2004
Riddarhusets medalj	G	8	RhGGM8	2002/2004
Markstridsskolans förtjänstmedalj	G/S	8	MSSGM/SM	2002
Militärhögskolan Karlberg förtjänstmedalj	G/S/B	8	MHSKGM/SM/BM	2002
Militärhögskolan Östersunds förtjänstmedalj	G/S/B	8	MHSÖGM/SM/BM	2002
Militärhögskolan Halmstad förtjänstmedalj	G/S/B	8	MHSHGM/SM/BM	2002
Västerbottengruppens förtjänstmedalj	G	8	VbottengrpGM	2002
Älvsborgsgruppens förtjänstmedalj	G	8	ÄlvsbgrpGM	2002
Sveriges Civilförsvarsförbunds hederstecken	G	8	SCFGHt	2002
Svenska Heraldiska Föreningens förtjänstmedalj	G	8	SHFGM	2002
Mellersta militärdistriktets förtjänstmedalj	G/S	8	MMDGM/SM	2003
Frivilliga Skytterörelsens Hedersmedalj	S	8	FrivSkytteHSM	2003
Södermanlands regementes förtjänstmedalj i guld	G/S	8	SödermlregGM/SM	2003
Livgardets förtjänstmedalj III	G/S	8	LG IIIGM/SM	2004
Norrbottens gränsjägargrupps förtjänstmedalj	G	8	NorrbgrjgrpGM	2004
Helikopterflottiljens förtjänstmedalj	G/S	8	HkpfljGM/SM	2005/2011
Förbundet Sveriges reservofficerares förtjänsttecken	G	8	SVEROGGft	2006
Thorsten Bergstrand-medaljen för internationellt arbete	S	8	TBSM	2006
Trängregementets förtjänstmedalj	G/S	8	TrängRGM/SM	2007
Ledningsregementets förtjänstmedalj	G/S	8	LedRGM/SM	2007
Skaraborgs flygflottiljs förtjänstmedalj	G/S	8	SkarabffljGM/SM	2007
Sjöstridsskolans förtjänstmedalj	G/S	8	SSSGFM/SM	2009
Göta ingenjörregementes förtjänstmedalj	G/S	8	Ing2FGM/SM	2009
FMTS guldförtjänstmedalj	G/S	8	FMTSGM/SM	2009
Högkvarterets guldförtjänstmedalj	G/S	8	HKVGM/SM	2010
Svenska Pistolskytteförbundets Jubileumsmedalj	S	8	SvpistskfbJSM	2011
Försvarsmedicincentrums guldförtjänstmedalj	G/S	8	FömedCGM/SM	2011
@@PRIMARY@@
1	Hemvärnets silvermedalj	HvSMmkrans|HvSM	1951
2	Hemvärnets bronsmedalj	HvBMmkrans|HvBMm3stjärn|HvBMm2stjärn|HvBM	2006
@@GROUP	1	Övriga icke officiella förtjänstmedaljer i kategori L	legacy
@@GROUP	2	Minnesmedaljer i kategori L	legacy
Skånska dragonregementets minnesmedalj	S	8	SkåndragregMSM	1994
Norra skånska regementets minnesmedalj	S	8	NSkånregMSM	1994
Skånska trängbataljonens minnesmedalj	S	8	SkåntrbatMSM	1994
Livgrenadjär regementets minnesmedalj	S	8	LivregMSM	1996
Svenska Värnpliksofficersförbundets minnestecken med kvist	B	8	SVOFBMtmkvist	1996
Svenska Värnpliksofficersförbundets minnestecken	B	8	SVOFBMt	1996
Kronobergs regementes minnesmedalj	S	8	KronobregMM	1997
Lapplandsbrigadens minnesmedalj	S	8	LapplbrigMM	1997
Norrlands Artilleriregementes minnesmedalj (A 4)	S	8	NorrlartregMM	1997
Svea Artilleriregementes minnesmedalj	S	8	SveaartregMM	1997
Skånska luftvärnskårens minnesmedalj	S	8	SkånlvkMM	1997
Svea ingenjörkårs minnesmedalj	S	8	SveaingkMM	1997
Svea trängkårs minnesmedalj	S	8	SveatrkMM	1997
Arméns underhållscentrums minnesmedalj	S	8	UhCMM	1997
Kalmar regementes minnesmedalj	S	8	KalmarregMM	1997
Nedre Norra arméfördelningens minnesmedalj	S	8	NedNorrfördMM	1997
Mellersta fördelningens minnesmedalj	S	8	MelfördMM	1997
Västra arméfördelningens förtjänstmedalj	S	8	VFördFM	1997
Norrlands Signalregementes minnesmedalj	S	8	NorrsignMM	1998
Krigsskolans minnesmedalj	S	8	KSMM	1998
Älvsborgs regementes minnesmedalj	S	8	ÄlvsbregMM	1999
Göta Helikopterbataljons minnesmedalj	S	8	GötahkpbatMM	1999
Härnösands kustartilleriregementes minnesmedalj	S	8	HärnkaregMSM	1999
Värmlands regementes och Värmlandsbrigadens minnesmedalj	S	8	VärmlregbrigMSM	2000
Livregementets grenadjärers minnesmedalj	S	8	LivreggrenMSM	2000
Smålands regementes och Smålandsbrigadens minnesmedalj	S	8	SmålregbrigMSM	2000
Dalregementet och Dalabrigadens minnesmedalj	S	8	DalregbrigMSM	2000
Hallands regementes och Hallandsbrigadens minnesmedalj	S	8	HallregbrigMSM	2000
Västerbottens regementes minnesmedalj	S	8	VbottenregMSM	2000
Västernorrlands regementes minnesmedalj	S	8	VnorrlregMSM	2000
Lapplands jägarregementes minnesmedalj	S	8	LappljregMSM	2000
Skånska Dragonbrigadens minnesmedalj	S	8	SkåndragbrigMM	2000
Gotlands artilleriregementes minnesmedalj	S	8	GotartregMM	2000
Gotlands luftvärnskårs minnesmedalj	S	8	GotlvkMM	2000
Roslagens luftvärnskårs minnesmedalj	S	8	RosllvkMM	2000
Göta Luftvärnskårs minnesmedalj	S	8	GötlvkMM	2000
Norrlands luftvärnskårs minnesmedalj	S	8	NorrllvkMM	2000
Norrlands ingenjörkårs minnesmedalj	S	8	NorrlingMM	2000
Norrlands trängkårs minnesmedalj	S	8	NorrltrkMM	2000
Västra Marinkommandots minnesmedalj	S	8	MKVMM	2000
Norra Marinkommandots minnesmedalj	S	8	MKNMSM	2000
Östra arméfördelningens minnesmedalj	S	8	ÖFördMSM	2000
Karlskrona kustartilleriregementes minnesmedalj	S	8	KarlskaregMSM	2000
Gotlands kustartilleriregementes minnesmedalj	S	8	GotkaregMSM	2000
Norrbottens gränsjägares minnesmedalj	S	8	NorrbgrjMSM	2000
Uppland-Västmanlands försvarsområdes minnesmedalj	S	8	UppVästföMSM	2000
Norra arméfördelningens minnesmedalj	S	8	NFördMSM	2000
Södra arméfördelningens minnesmedalj	S	8	SFördMSM	2000
Mellersta militärområdesstabens minnesmedalj	S	8	MiloMMSM	2000
Norra militärområdesstabens minnesmedalj	S	8	MiloNMSM	2000
Norrlands artilleriregemente minnesmedalj (A 8)	S	8	NorrlartregMM	2000
Södra militärområdesstabens minnesmedalj	S	8	MiloSMSM	2000
Wendes artilleriregementes minnesmedalj	S	8	WendesArtregMSM	2000
Svenska Värnpliksofficersförbundets minnestecken i guld vid 100 års jubileet för värnplikten	G	8	VploffMt	2000
Försvarsmaktens underhållscentrums minnesmedalj	B	8	FMUHCMBM	2001
Mellersta Underhållsregementets minnesmedalj	S	8	UHregMMSM	2001
Norra Underhållsregementets minnesmedalj	S	8	UHregNMSM	2001
Södra Underhållsregementets minnesmedalj	S	8	UHregSMSM	2001
Svenska Värnpliksofficersförbundets minnesmedalj till minnet av organisationsförändringen	G	8	VploffMGM	2002
Carolus Rex Revivat minnestecken i guld	G	8	CRRGMt	2002
Upplands flyglottiljs minnesmedalj	S/B	8	UpplffljMSM/BM	2003
Försvarsmaktens internationella centrum minnesmedalj	S	8	SWEDINTMSM	2003
Svenska Värnpliktsofficersförbundets minnesmedalj med anledning av organisationsförändringen 2003	B	8	SvVoffMGM	2003
Norrlands Dragonregementes minnesmedalj	S	8	NorrldragregMSM	2004
Försvarsmaktens Halmstadskolors minnesmedalj	S	8	FMHMSMSM	2004
Jämtlands fältjägararregemente och Östersunds garnisons minnesmedalj	S	8	JämtlfältjregMSM	2005
Södermanlands regementes minnesmedalj	S	8	SödermlregMSM	2005
Gotlands regementes minnesmedalj	S	8	GotregMSM	2005
Norrlands Artilleribataljons minnesmedalj	S	8	NorrlartbatMSM	2005
Bodens artilleriregementes minnesmedalj	S	8	BodensartregMSM	2005
Upplands regementes minnesmedalj	G	8	UpplregMBM	2005
Norrlands signalbataljons minnesmedalj	S	8	NorrlsignbatMSM	2005
Norrlands ingenjörbataljons minnesmedalj	S	8	NorrlingbatMSM	2005/2011
Norrlands luftvärnsbataljons minnesmedalj	S	8	NorrllvbatMSM|NorrlingbatMSMmbock	2005
Helikopterflottiljens minnesmedalj 1.hkpskv	S	8	1HkpskvMSM	2005
Helikopterflottiljens minnesmedalj 2.hkpskv	S	8	2HkpskvMSM	2005
Helikopterflottiljens minnesmedalj 4.hkpskv	S	8	4HkpskvMSM	2005
Helikopterflottiljens minnesmedalj 5.hkpskv	S	8	5HkpskvMSM	2005
HMS Carlskronas minnesmedalj	S	8	CarskrMSM	2005
Örlogsskolornas minnesmedalj	S	8	ÖSMSM	2005
Ostkustens Marinbas minnesmedalj	S	8	MarinBOMSM	2005
Andra Ytstridsflottiljens minnesmedalj	G	8	2YsfljMM	2005
Älvsborgs amfibieregementes minnesmedalj	G	8	ÄlvsbamfregMGM	2005
Jämtlands flygflottiljs minnesmedalj	S	8	JämtfflMSM	2005
Arméns tekniska skolas minnesmedalj	S	8	ATSMSM	2005
Mellersta militärdistriktets minnesmedalj	S	8	MMDMSM	2005
Norra militärdistriktets minnesmedalj	B	8	MDNMBM	2005
Södra militärdistriktets minnesmedalj	S	8	SMDMSM	2005
Gotlands militärdistrikts minnesmedalj	S	8	MDGMSM	2005
Järnvägarnas driftvärns minnesmedalj	S	8	JvgDvMSM	2005
Artilleriregementets minnesmedalj	B	8	ArtRegMBM	2005
Amfibiestridsskolans minnesmedalj	S	8	AmfSSMM	2005
4. Minkrigsflottiljens minnesmedalj	G	8	4MinkrigfljMM	2006
Driftvärnets minnesmedalj	S	8	DriftvMSM	2006
Svenska Värnpliktofficersförbundets minnesmedalj med anledning av förbundets upplösning 2006	G	8	SvVoff2MGM	2006
Flygmedicincentrums minnesmedalj	S	8	FMCMM	2006
Hallands Försvarsutbildningsförbunds 100års minnesmedalj	S	8	HallfufMSM	2008
Försvarshögskolans minnesmedalj	G/S/B	8	FHSMGM/SM/BM	2008
Försvarsmusikcentrums minnesmedalj	B	8	FöMusCBMM	2009
Väg- och vattenbyggnadskårens minnesmedalj	B	8	VVKBMM	2010
Försvarsutbildarna i Stockholms Jubileumsmedalj 1908-2008	G/S	8	FöutbSthJGM/SM	2010
@@GROUP	3	Särskilda svenska utmärkelsetecken utan band	initial-number
1	Riksförbundet Sveriges Lottakårers förtjänsttecken	SLKFt
2	Sveriges Bilkårers förtjänsttecken (f.d. Sveriges kvinnliga bilkårers förtjänsttecken)	SKBRGFtm3rub|SKBRGFtm2rub|SKBRGFtm1rub|SKBRGFtmoem|SKBRGFtmgem|SKBRGFttvem|SKBRGFtmrem|SKBRGFt|SKBRGFt2
$category_l$, E'\n') WITH ORDINALITY AS t(line, ordinality)
            LOOP
                IF raw_line = '' THEN
                    CONTINUE;
                END IF;

                IF raw_line = '@@PRIMARY@@' THEN
                    section := 'primary';
                    CONTINUE;
                END IF;

                IF raw_line LIKE '@@GROUP%' THEN
                    parts := string_to_array(raw_line, E'\t');

                    IF parts[2] = '1' THEN
                        section := 'l_grp_1';
                    ELSIF parts[2] = '2' THEN
                        section := 'l_grp_2';
                    ELSIF parts[2] = '3' THEN
                        section := 'l_grp_3';
                    END IF;

                    CONTINUE;
                END IF;

                parts := string_to_array(raw_line, E'\t');

                IF section = 'primary' THEN
                    primary_display_order := primary_display_order + 1;

                    INSERT INTO decoration (category_id, subcategory_id, name_sv, name_en, initial_number,
                                            year_display, year_sort, description_sv, description_en, display_order)
                    VALUES (category_l_id, NULL, parts[2], parts[2], parts[1]::integer,
                            parts[4], NULL, NULL, NULL, primary_display_order)
                    RETURNING id INTO inserted_decoration_id;

                    INSERT INTO decoration_category_l_detail (decoration_id, source_model, award_levels, medal_size,
                                                              raw_short_code_text, source_line_no)
                    VALUES (inserted_decoration_id, 'primary', NULL, NULL, parts[3], src_line_no);

                    INSERT INTO decoration_short_code (decoration_id, short_code, display_order, description_sv,
                                                       description_en)
                    SELECT inserted_decoration_id,
                           trim(code),
                           ord::integer,
                           NULL,
                           NULL
                    FROM unnest(string_to_array(parts[3], '|')) WITH ORDINALITY AS short_codes(code, ord);

                ELSIF section = 'l_grp_1' THEN
                    group_1_display_order := group_1_display_order + 1;

                    INSERT INTO decoration (category_id, subcategory_id, name_sv, name_en, initial_number,
                                            year_display, year_sort, description_sv, description_en, display_order)
                    VALUES (NULL, subcategory_group_1_id, parts[1], parts[1], NULL,
                            parts[5], NULL, NULL, NULL, group_1_display_order)
                    RETURNING id INTO inserted_decoration_id;

                    INSERT INTO decoration_category_l_detail (decoration_id, source_model, award_levels, medal_size,
                                                              raw_short_code_text, source_line_no)
                    VALUES (inserted_decoration_id, 'legacy', NULLIF(parts[2], ''), NULLIF(parts[3], ''), parts[4],
                            src_line_no);

                    INSERT INTO decoration_short_code (decoration_id, short_code, display_order, description_sv,
                                                       description_en)
                    SELECT inserted_decoration_id,
                           trim(code),
                           ord::integer,
                           NULL,
                           NULL
                    FROM unnest(string_to_array(parts[4], '|')) WITH ORDINALITY AS short_codes(code, ord);

                ELSIF section = 'l_grp_2' THEN
                    group_2_display_order := group_2_display_order + 1;

                    INSERT INTO decoration (category_id, subcategory_id, name_sv, name_en, initial_number,
                                            year_display, year_sort, description_sv, description_en, display_order)
                    VALUES (NULL, subcategory_group_2_id, parts[1], parts[1], NULL,
                            parts[5], NULL, NULL, NULL, group_2_display_order)
                    RETURNING id INTO inserted_decoration_id;

                    INSERT INTO decoration_category_l_detail (decoration_id, source_model, award_levels, medal_size,
                                                              raw_short_code_text, source_line_no)
                    VALUES (inserted_decoration_id, 'legacy', NULLIF(parts[2], ''), NULLIF(parts[3], ''), parts[4],
                            src_line_no);

                    INSERT INTO decoration_short_code (decoration_id, short_code, display_order, description_sv,
                                                       description_en)
                    SELECT inserted_decoration_id,
                           trim(code),
                           ord::integer,
                           NULL,
                           NULL
                    FROM unnest(string_to_array(parts[4], '|')) WITH ORDINALITY AS short_codes(code, ord);

                ELSIF section = 'l_grp_3' THEN
                    group_3_display_order := group_3_display_order + 1;

                    INSERT INTO decoration (category_id, subcategory_id, name_sv, name_en, initial_number,
                                            year_display, year_sort, description_sv, description_en, display_order)
                    VALUES (NULL, subcategory_group_3_id, parts[2], parts[2], parts[1]::integer,
                            NULL, NULL, NULL, NULL, group_3_display_order)
                    RETURNING id INTO inserted_decoration_id;

                    INSERT INTO decoration_category_l_detail (decoration_id, source_model, award_levels, medal_size,
                                                              raw_short_code_text, source_line_no)
                    VALUES (inserted_decoration_id, 'initial-number', NULL, NULL, parts[3], src_line_no);

                    INSERT INTO decoration_short_code (decoration_id, short_code, display_order, description_sv,
                                                       description_en)
                    SELECT inserted_decoration_id,
                           trim(code),
                           ord::integer,
                           NULL,
                           NULL
                    FROM unnest(string_to_array(parts[3], '|')) WITH ORDINALITY AS short_codes(code, ord);
                END IF;
            END LOOP;
    END
$plpgsql$;

